name: string_mask
description: A string formatter and validator based on masks.
version: 0.2.0
homepage: https://www.olimou.com
author: EmersonMoura <olimou@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.4.0
